"""Contribution record: a track record the next maintainer can verify in a minute.

Built only from public GitHub data and every line links to its source, so
it can't be padded. It highlights what maintainers actually care about:
merged work, follow-through after review, and honest explanations.
"""

from __future__ import annotations

import html
import re
from dataclasses import dataclass, field
from datetime import datetime

from .github import GitHub

UNDERSTANDING = re.compile(r"^#+\s*(understanding|why|root cause|explanation)\b", re.I | re.M)
AI_NOTE = re.compile(r"^#+\s*ai (assistance|use|disclosure)|\b(ai[- ]assisted|used (an )?ai|no ai (was )?used|"
                     r"generated with|copilot|chatgpt|claude)\b", re.I | re.M)


@dataclass
class PREntry:
    repo: str
    number: int
    title: str
    url: str
    state: str            # merged, open, closed
    created: str
    closed: str | None
    review_rounds: int = 0
    answered_reviews: bool | None = None
    explained: bool = False
    ai_disclosed: bool = False


@dataclass
class Record:
    user: str
    prs: list[PREntry] = field(default_factory=list)

    @property
    def merged(self) -> list[PREntry]:
        return [p for p in self.prs if p.state == "merged"]

    @property
    def repos(self) -> list[str]:
        return sorted({p.repo for p in self.merged})


def build(gh: GitHub, user: str, limit: int = 30, include_own: bool = False) -> Record:
    rec = Record(user)
    items = gh.search_issues(f"author:{user} type:pr is:public", per_page=limit)
    for it in items:
        m = re.search(r"repos/([^/]+)/([^/]+)/issues/(\d+)", it["url"])
        if not m:
            continue
        owner, name, num = m.group(1), m.group(2), int(m.group(3))
        if owner.lower() == user.lower() and not include_own:
            continue  # the record is about contributing to other people's projects
        merged_at = (it.get("pull_request") or {}).get("merged_at")
        state = "merged" if merged_at else ("open" if it["state"] == "open" else "closed")
        body = it.get("body") or ""
        e = PREntry(f"{owner}/{name}", num, it["title"], it["html_url"], state, it["created_at"],
                    merged_at or it.get("closed_at"), explained=bool(UNDERSTANDING.search(body)),
                    ai_disclosed=bool(AI_NOTE.search(body)))
        reviews = gh.pr_reviews(owner, name, num)
        e.review_rounds = sum(1 for r in reviews if r.get("state") == "CHANGES_REQUESTED")
        if e.review_rounds:
            comments = gh.pr_review_comments(owner, name, num)
            others = [c for c in comments if c["user"]["login"] != user and not c.get("in_reply_to_id")]
            mine = {c.get("in_reply_to_id") for c in comments if c["user"]["login"] == user}
            e.answered_reviews = all(c["id"] in mine for c in others) if others else True
        rec.prs.append(e)
    return rec


def _date(ts: str | None) -> str:
    return datetime.fromisoformat(ts.replace("Z", "+00:00")).strftime("%Y-%m-%d") if ts else ""


def to_markdown(r: Record) -> str:
    done = [p for p in r.prs if p.state != "open"]
    L = [f"# Contribution record: @{r.user}", ""]
    L.append(f"**{len(r.merged)} merged** PR(s) across {len(r.repos)} project(s)"
             + (f", out of {len(done)} finished." if done else "."))
    reviewed = [p for p in r.prs if p.answered_reviews is not None]
    if reviewed:
        ok = sum(p.answered_reviews for p in reviewed)
        L.append(f"Answered every review comment on {ok} of {len(reviewed)} PR(s) that got change requests.")
    L.append(f"Explained the change in their own words on {sum(p.explained for p in r.prs)} PR(s); "
             f"disclosed AI use on {sum(p.ai_disclosed for p in r.prs)}.")
    L += ["", "| PR | Status | Review rounds | Explained | AI disclosed |", "|---|---|---|---|---|"]
    for p in r.prs:
        L.append(f"| [{p.repo}#{p.number}]({p.url}) {_short(p.title, 60)} | {p.state} {_date(p.closed or p.created)} | "
                 f"{p.review_rounds} | {'yes' if p.explained else '–'} | {'yes' if p.ai_disclosed else '–'} |")
    L += ["", "_Every row links to GitHub. Generated by ContribOS from public data._"]
    return "\n".join(L)


def to_html(r: Record) -> str:
    e = html.escape
    rows = "\n".join(
        f"<tr><td><a href='{e(p.url)}'>{e(p.repo)}#{p.number}</a><div class='t'>{e(p.title)}</div></td>"
        f"<td><span class='s {p.state}'>{p.state}</span><div class='t'>{_date(p.closed or p.created)}</div></td>"
        f"<td>{p.review_rounds}</td><td>{'✓' if p.explained else '–'}</td><td>{'✓' if p.ai_disclosed else '–'}</td></tr>"
        for p in r.prs)
    done = len([p for p in r.prs if p.state != "open"])
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>@{e(r.user)} · Contribution record</title>
<style>
:root{{--bg:#fbfaf7;--fg:#1d1c1a;--mut:#6b6862;--line:#e6e2da;--ok:#1f7a4d;--no:#a33b2c;--open:#8a6d1a}}
@media (prefers-color-scheme:dark){{:root{{--bg:#161513;--fg:#ece9e3;--mut:#a09b92;--line:#2c2a26;--ok:#5cc28f;--no:#e0806f;--open:#d8b85a}}}}
body{{background:var(--bg);color:var(--fg);font:15px/1.5 system-ui,sans-serif;margin:0;padding:32px 16px}}
main{{max-width:880px;margin:auto}} h1{{font-size:26px;margin:0 0 4px}} .mut,.t{{color:var(--mut)}} .t{{font-size:13px}}
.stats{{display:flex;gap:28px;flex-wrap:wrap;margin:24px 0}} .stats b{{display:block;font-size:28px}}
table{{width:100%;border-collapse:collapse}} td,th{{text-align:left;padding:10px 8px;border-top:1px solid var(--line);vertical-align:top}}
th{{font-size:12px;color:var(--mut);font-weight:600;text-transform:uppercase;letter-spacing:.04em}}
a{{color:inherit}} .s{{font-weight:600}} .merged{{color:var(--ok)}} .closed{{color:var(--no)}} .open{{color:var(--open)}}
.wrap{{overflow-x:auto}}
</style></head><body><main>
<h1>@{e(r.user)}</h1><div class="mut">Open-source contribution record · every row links to GitHub</div>
<div class="stats"><div><b>{len(r.merged)}</b><span class="mut">merged PRs</span></div>
<div><b>{len(r.repos)}</b><span class="mut">projects</span></div>
<div><b>{done}</b><span class="mut">finished PRs</span></div>
<div><b>{sum(p.explained for p in r.prs)}</b><span class="mut">explained in own words</span></div></div>
<div class="wrap"><table><tr><th>PR</th><th>Status</th><th>Change requests</th><th>Explained</th><th>AI disclosed</th></tr>
{rows}</table></div>
<p class="mut t">Generated by ContribOS from public GitHub data.</p>
</main></body></html>"""


def _short(text: str, n: int) -> str:
    return text if len(text) <= n else text[:n - 1].rstrip() + "…"
